#ifndef PROTO_MATHIEEEDOUBTRANS_H
#define PROTO_MATHIEEEDOUBTRANS_H

/*
    Copyright © 1995-2004, The AROS Development Team. All rights reserved.
    Automatically generated by /home/adam/Build/20051008/AROS/bin/linux-i386/gen/scripts/genshared
*/

#ifndef AROS_SYSTEM_H
#   include <aros/system.h>
#endif

#include <clib/mathieeedoubtrans_protos.h>
#include <defines/mathieeedoubtrans.h>

#endif /* PROTO_MATHIEEEDOUBTRANS_H */
