#ifndef DEFINES_MATHIEEEDOUBTRANS_PROTOS_H
#define DEFINES_MATHIEEEDOUBTRANS_PROTOS_H

/*
    Copyright © 1995-2003, The AROS Development Team. All rights reserved.
    *** Automatically generated by gendefines.awk. Do not edit ***

    Desc: Prototypes for MathIeeeDoubTrans
    Lang: english
*/

#ifndef AROS_LIBCALL_H
#   include <aros/libcall.h>
#endif
#ifndef EXEC_TYPES_H
#   include <exec/types.h>
#endif
#ifndef AROS_PREPROCESSOR_VARIADIC_CAST2IPTR_HPP
#   include <aros/preprocessor/variadic/cast2iptr.hpp>
#endif

#define __IEEEDPAcos_WB(__MathIeeeDoubTransBase, __x)\
    AROS_LC1(double, IEEEDPAcos, \
    AROS_LCA(double, (__x), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 20, MathIeeeDoubTrans)

#define IEEEDPAcos(x)\
    __IEEEDPAcos_WB(MathIeeeDoubTransBase, (x))

#define __IEEEDPAsin_WB(__MathIeeeDoubTransBase, __x)\
    AROS_LC1(double, IEEEDPAsin, \
    AROS_LCA(double, (__x), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 19, MathIeeeDoubTrans)

#define IEEEDPAsin(x)\
    __IEEEDPAsin_WB(MathIeeeDoubTransBase, (x))

#define __IEEEDPAtan_WB(__MathIeeeDoubTransBase, __y)\
    AROS_LC1(double, IEEEDPAtan, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 5, MathIeeeDoubTrans)

#define IEEEDPAtan(y)\
    __IEEEDPAtan_WB(MathIeeeDoubTransBase, (y))

#define __IEEEDPCos_WB(__MathIeeeDoubTransBase, __y)\
    AROS_LC1(double, IEEEDPCos, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 7, MathIeeeDoubTrans)

#define IEEEDPCos(y)\
    __IEEEDPCos_WB(MathIeeeDoubTransBase, (y))

#define __IEEEDPCosh_WB(__MathIeeeDoubTransBase, __y)\
    AROS_LC1(double, IEEEDPCosh, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 11, MathIeeeDoubTrans)

#define IEEEDPCosh(y)\
    __IEEEDPCosh_WB(MathIeeeDoubTransBase, (y))

#define __IEEEDPExp_WB(__MathIeeeDoubTransBase, __y)\
    AROS_LC1(double, IEEEDPExp, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 13, MathIeeeDoubTrans)

#define IEEEDPExp(y)\
    __IEEEDPExp_WB(MathIeeeDoubTransBase, (y))

#define __IEEEDPFieee_WB(__MathIeeeDoubTransBase, __y)\
    AROS_LC1(double, IEEEDPFieee, \
    AROS_LCA(LONG, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 18, MathIeeeDoubTrans)

#define IEEEDPFieee(y)\
    __IEEEDPFieee_WB(MathIeeeDoubTransBase, (y))

#define __IEEEDPLog10_WB(__MathIeeeDoubTransBase, __y)\
    AROS_LC1(double, IEEEDPLog10, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 21, MathIeeeDoubTrans)

#define IEEEDPLog10(y)\
    __IEEEDPLog10_WB(MathIeeeDoubTransBase, (y))

#define __IEEEDPLog_WB(__MathIeeeDoubTransBase, __y)\
    AROS_LC1(double, IEEEDPLog, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 14, MathIeeeDoubTrans)

#define IEEEDPLog(y)\
    __IEEEDPLog_WB(MathIeeeDoubTransBase, (y))

#define __IEEEDPPow_WB(__MathIeeeDoubTransBase, __x, __y)\
    AROS_LC2(double, IEEEDPPow, \
    AROS_LCA(double, (__x), D2), \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 15, MathIeeeDoubTrans)

#define IEEEDPPow(x, y)\
    __IEEEDPPow_WB(MathIeeeDoubTransBase, (x), (y))

#define __IEEEDPSin_WB(__MathIeeeDoubTransBase, __y)\
    AROS_LC1(double, IEEEDPSin, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 6, MathIeeeDoubTrans)

#define IEEEDPSin(y)\
    __IEEEDPSin_WB(MathIeeeDoubTransBase, (y))

#define __IEEEDPSincos_WB(__MathIeeeDoubTransBase, __z, __y)\
    AROS_LC2(double, IEEEDPSincos, \
    AROS_LCA(double *, (__z), A0), \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 9, MathIeeeDoubTrans)

#define IEEEDPSincos(z, y)\
    __IEEEDPSincos_WB(MathIeeeDoubTransBase, (z), (y))

#define __IEEEDPSinh_WB(__MathIeeeDoubTransBase, __y)\
    AROS_LC1(double, IEEEDPSinh, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 10, MathIeeeDoubTrans)

#define IEEEDPSinh(y)\
    __IEEEDPSinh_WB(MathIeeeDoubTransBase, (y))

#define __IEEEDPSqrt_WB(__MathIeeeDoubTransBase, __y)\
    AROS_LC1(double, IEEEDPSqrt, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 16, MathIeeeDoubTrans)

#define IEEEDPSqrt(y)\
    __IEEEDPSqrt_WB(MathIeeeDoubTransBase, (y))

#define __IEEEDPTanh_WB(__MathIeeeDoubTransBase, __y)\
    AROS_LC1(double, IEEEDPTanh, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 12, MathIeeeDoubTrans)

#define IEEEDPTanh(y)\
    __IEEEDPTanh_WB(MathIeeeDoubTransBase, (y))

#define __IEEEDPTieee_WB(__MathIeeeDoubTransBase, __y)\
    AROS_LC1(LONG, IEEEDPTieee, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubTransBase *, (__MathIeeeDoubTransBase), 17, MathIeeeDoubTrans)

#define IEEEDPTieee(y)\
    __IEEEDPTieee_WB(MathIeeeDoubTransBase, (y))

#endif /* DEFINES_MATHIEEEDOUBTRANS_PROTOS_H */
