#ifndef DEFINES_MATHIEEEDOUBBAS_PROTOS_H
#define DEFINES_MATHIEEEDOUBBAS_PROTOS_H

/*
    Copyright © 1995-2003, The AROS Development Team. All rights reserved.
    *** Automatically generated by gendefines.awk. Do not edit ***

    Desc: Prototypes for MathIeeeDoubBas
    Lang: english
*/

#ifndef AROS_LIBCALL_H
#   include <aros/libcall.h>
#endif
#ifndef EXEC_TYPES_H
#   include <exec/types.h>
#endif
#ifndef AROS_PREPROCESSOR_VARIADIC_CAST2IPTR_HPP
#   include <aros/preprocessor/variadic/cast2iptr.hpp>
#endif

#define __IEEEDPAbs_WB(__MathIeeeDoubBasBase, __y)\
    AROS_LC1(double, IEEEDPAbs, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubBasBase *, (__MathIeeeDoubBasBase), 9, MathIeeeDoubBas)

#define IEEEDPAbs(y)\
    __IEEEDPAbs_WB(MathIeeeDoubBasBase, (y))

#define __IEEEDPAdd_WB(__MathIeeeDoubBasBase, __y, __z)\
    AROS_LC2(double, IEEEDPAdd, \
    AROS_LCA(double, (__y), D0), \
    AROS_LCA(double, (__z), D2), \
    struct MathIeeeDoubBasBase *, (__MathIeeeDoubBasBase), 11, MathIeeeDoubBas)

#define IEEEDPAdd(y, z)\
    __IEEEDPAdd_WB(MathIeeeDoubBasBase, (y), (z))

#define __IEEEDPCeil_WB(__MathIeeeDoubBasBase, __y)\
    AROS_LC1(double, IEEEDPCeil, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubBasBase *, (__MathIeeeDoubBasBase), 16, MathIeeeDoubBas)

#define IEEEDPCeil(y)\
    __IEEEDPCeil_WB(MathIeeeDoubBasBase, (y))

#define __IEEEDPCmp_WB(__MathIeeeDoubBasBase, __y, __z)\
    AROS_LC2(LONG, IEEEDPCmp, \
    AROS_LCA(double, (__y), D0), \
    AROS_LCA(double, (__z), D2), \
    struct MathIeeeDoubBasBase *, (__MathIeeeDoubBasBase), 7, MathIeeeDoubBas)

#define IEEEDPCmp(y, z)\
    __IEEEDPCmp_WB(MathIeeeDoubBasBase, (y), (z))

#define __IEEEDPDiv_WB(__MathIeeeDoubBasBase, __y, __z)\
    AROS_LC2(double, IEEEDPDiv, \
    AROS_LCA(double, (__y), D0), \
    AROS_LCA(double, (__z), D2), \
    struct MathIeeeDoubBasBase *, (__MathIeeeDoubBasBase), 14, MathIeeeDoubBas)

#define IEEEDPDiv(y, z)\
    __IEEEDPDiv_WB(MathIeeeDoubBasBase, (y), (z))

#define __IEEEDPFix_WB(__MathIeeeDoubBasBase, __y)\
    AROS_LC1(LONG, IEEEDPFix, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubBasBase *, (__MathIeeeDoubBasBase), 5, MathIeeeDoubBas)

#define IEEEDPFix(y)\
    __IEEEDPFix_WB(MathIeeeDoubBasBase, (y))

#define __IEEEDPFloor_WB(__MathIeeeDoubBasBase, __y)\
    AROS_LC1(double, IEEEDPFloor, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubBasBase *, (__MathIeeeDoubBasBase), 15, MathIeeeDoubBas)

#define IEEEDPFloor(y)\
    __IEEEDPFloor_WB(MathIeeeDoubBasBase, (y))

#define __IEEEDPFlt_WB(__MathIeeeDoubBasBase, __y)\
    AROS_LC1(double, IEEEDPFlt, \
    AROS_LCA(LONG, (__y), D0), \
    struct MathIeeeDoubBasBase *, (__MathIeeeDoubBasBase), 6, MathIeeeDoubBas)

#define IEEEDPFlt(y)\
    __IEEEDPFlt_WB(MathIeeeDoubBasBase, (y))

#define __IEEEDPMul_WB(__MathIeeeDoubBasBase, __y, __z)\
    AROS_LC2(double, IEEEDPMul, \
    AROS_LCA(double, (__y), D0), \
    AROS_LCA(double, (__z), D2), \
    struct MathIeeeDoubBasBase *, (__MathIeeeDoubBasBase), 13, MathIeeeDoubBas)

#define IEEEDPMul(y, z)\
    __IEEEDPMul_WB(MathIeeeDoubBasBase, (y), (z))

#define __IEEEDPNeg_WB(__MathIeeeDoubBasBase, __y)\
    AROS_LC1(double, IEEEDPNeg, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubBasBase *, (__MathIeeeDoubBasBase), 10, MathIeeeDoubBas)

#define IEEEDPNeg(y)\
    __IEEEDPNeg_WB(MathIeeeDoubBasBase, (y))

#define __IEEEDPSub_WB(__MathIeeeDoubBasBase, __y, __z)\
    AROS_LC2(double, IEEEDPSub, \
    AROS_LCA(double, (__y), D0), \
    AROS_LCA(double, (__z), D2), \
    struct MathIeeeDoubBasBase *, (__MathIeeeDoubBasBase), 12, MathIeeeDoubBas)

#define IEEEDPSub(y, z)\
    __IEEEDPSub_WB(MathIeeeDoubBasBase, (y), (z))

#define __IEEEDPTst_WB(__MathIeeeDoubBasBase, __y)\
    AROS_LC1(LONG, IEEEDPTst, \
    AROS_LCA(double, (__y), D0), \
    struct MathIeeeDoubBasBase *, (__MathIeeeDoubBasBase), 8, MathIeeeDoubBas)

#define IEEEDPTst(y)\
    __IEEEDPTst_WB(MathIeeeDoubBasBase, (y))

#endif /* DEFINES_MATHIEEEDOUBBAS_PROTOS_H */
