#ifndef CLIB_MATHIEEEDOUBBAS_PROTOS_H
#define CLIB_MATHIEEEDOUBBAS_PROTOS_H

/*
    Copyright © 1995-2003, The AROS Development Team. All rights reserved.
    *** Automatically generated by genclib.awk. Do not edit ***

    Desc: Prototypes for MathIeeeDoubBas.library
    Lang: english
*/

#ifndef AROS_LIBCALL_H
#   include <aros/libcall.h>
#endif

/* Prototypes */
AROS_LPQUAD1(double, IEEEDPAbs,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubBasBase *, MathIeeeDoubBasBase, 9, MathIeeeDoubBas)

AROS_LPQUAD2(double, IEEEDPAdd,
	AROS_LPAQUAD(double, y, D0, D1),
	AROS_LPAQUAD(double, z, D2, D3),
	struct MathIeeeDoubBasBase *, MathIeeeDoubBasBase, 11, MathIeeeDoubBas)

AROS_LPQUAD1(double, IEEEDPCeil,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubBasBase *, MathIeeeDoubBasBase, 16, MathIeeeDoubBas)

AROS_LPQUAD2(LONG, IEEEDPCmp,
	AROS_LPAQUAD(double, y, D0, D1),
	AROS_LPAQUAD(double, z, D2, D3),
	struct MathIeeeDoubBasBase *, MathIeeeDoubBasBase, 7, MathIeeeDoubBas)

AROS_LPQUAD2(double, IEEEDPDiv,
	AROS_LPAQUAD(double, y, D0, D1),
	AROS_LPAQUAD(double, z, D2, D3),
	struct MathIeeeDoubBasBase *, MathIeeeDoubBasBase, 14, MathIeeeDoubBas)

AROS_LPQUAD1(LONG, IEEEDPFix,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubBasBase *, MathIeeeDoubBasBase, 5, MathIeeeDoubBas)

AROS_LPQUAD1(double, IEEEDPFloor,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubBasBase *, MathIeeeDoubBasBase, 15, MathIeeeDoubBas)

AROS_LPQUAD1(double, IEEEDPFlt,
	AROS_LPAQUAD(LONG, y, D0, D1),
	struct MathIeeeDoubBasBase *, MathIeeeDoubBasBase, 6, MathIeeeDoubBas)

AROS_LPQUAD2(double, IEEEDPMul,
	AROS_LPAQUAD(double, y, D0, D1),
	AROS_LPAQUAD(double, z, D2, D3),
	struct MathIeeeDoubBasBase *, MathIeeeDoubBasBase, 13, MathIeeeDoubBas)

AROS_LPQUAD1(double, IEEEDPNeg,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubBasBase *, MathIeeeDoubBasBase, 10, MathIeeeDoubBas)

AROS_LPQUAD2(double, IEEEDPSub,
	AROS_LPAQUAD(double, y, D0, D1),
	AROS_LPAQUAD(double, z, D2, D3),
	struct MathIeeeDoubBasBase *, MathIeeeDoubBasBase, 12, MathIeeeDoubBas)

AROS_LPQUAD1(LONG, IEEEDPTst,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubBasBase *, MathIeeeDoubBasBase, 8, MathIeeeDoubBas)

#endif /* CLIB_MATHIEEEDOUBBAS_PROTOS_H */
