#ifndef CLIB_MATHIEEEDOUBTRANS_PROTOS_H
#define CLIB_MATHIEEEDOUBTRANS_PROTOS_H

/*
    Copyright © 1995-2003, The AROS Development Team. All rights reserved.
    *** Automatically generated by genclib.awk. Do not edit ***

    Desc: Prototypes for MathIeeeDoubTrans.library
    Lang: english
*/

#ifndef AROS_LIBCALL_H
#   include <aros/libcall.h>
#endif

/* Prototypes */
AROS_LPQUAD1(double, IEEEDPAcos,
	AROS_LPAQUAD(double, x, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 20, MathIeeeDoubTrans)

AROS_LPQUAD1(double, IEEEDPAsin,
	AROS_LPAQUAD(double, x, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 19, MathIeeeDoubTrans)

AROS_LPQUAD1(double, IEEEDPAtan,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 5, MathIeeeDoubTrans)

AROS_LPQUAD1(double, IEEEDPCos,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 7, MathIeeeDoubTrans)

AROS_LPQUAD1(double, IEEEDPCosh,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 11, MathIeeeDoubTrans)

AROS_LPQUAD1(double, IEEEDPExp,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 13, MathIeeeDoubTrans)

AROS_LPQUAD1(double, IEEEDPFieee,
	AROS_LPAQUAD(LONG, y, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 18, MathIeeeDoubTrans)

AROS_LPQUAD1(double, IEEEDPLog10,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 21, MathIeeeDoubTrans)

AROS_LPQUAD1(double, IEEEDPLog,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 14, MathIeeeDoubTrans)

AROS_LPQUAD2(double, IEEEDPPow,
	AROS_LPAQUAD(double, x, D2, D3),
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 15, MathIeeeDoubTrans)

AROS_LPQUAD1(double, IEEEDPSin,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 6, MathIeeeDoubTrans)

AROS_LP2(double, IEEEDPSincos,
	AROS_LPA(double *, z, A0),
	AROS_LPA(double, y, D0),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 9, MathIeeeDoubTrans)

AROS_LPQUAD1(double, IEEEDPSinh,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 10, MathIeeeDoubTrans)

AROS_LPQUAD1(double, IEEEDPSqrt,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 16, MathIeeeDoubTrans)

AROS_LPQUAD1(double, IEEEDPTanh,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 12, MathIeeeDoubTrans)

AROS_LPQUAD1(LONG, IEEEDPTieee,
	AROS_LPAQUAD(double, y, D0, D1),
	struct MathIeeeDoubTransBase *, MathIeeeDoubTransBase, 17, MathIeeeDoubTrans)

#endif /* CLIB_MATHIEEEDOUBTRANS_PROTOS_H */
